name: ci/cd pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run lint and tests
        run: |
          npm run lint
          npm test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/react-minikube:${{ github.sha }} .
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/react-minikube:${{ github.sha }}

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Set up kubectl
  #       uses: azure/setup-kubectl@v1
        
  #     - name: Deploy to Kubernetes (Minikube)
  #       env:
  #         KUBECONFIG: ${{ secrets.KUBECONFIG }}
  #       run: |
  #         kubectl apply -f k8s/deployment.yaml
  #         kubectl apply -f k8s/service.yaml
  #         kubectl set image deployment/react-app-deployment react-app=${{ secrets.DOCKER_USERNAME }}/my-react-app:${{ github.sha }}
